"""Edge baselines (Softmax/SVM/DecisionTree) using <=K hand-crafted features.

Design goals (for thesis Chapter 3):
- Keep the edge feature dimension small (K<=7 by default).
- Provide a *reproducible* feature selection procedure that uses only the
  validation set for choosing K, and never touches the test set.
- Export: selected feature list, coefficients, and metrics.

This script is meant to be called by the chapter-3 pipeline.

Author: generated by assistant
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier

from edge_features_allreal_v4 import feature_names_allreal_v4, extract_features_allreal_v4


EPS = 1e-9


def macro_f1(y_true: np.ndarray, y_pred: np.ndarray, n_class: int) -> float:
    f1s = []
    for c in range(n_class):
        tp = np.sum((y_true == c) & (y_pred == c))
        fp = np.sum((y_true != c) & (y_pred == c))
        fn = np.sum((y_true == c) & (y_pred != c))
        if tp == 0:
            f1 = 0.0
        else:
            p = tp / (tp + fp + EPS)
            r = tp / (tp + fn + EPS)
            f1 = 2 * p * r / (p + r + EPS)
        f1s.append(f1)
    return float(np.mean(f1s))


def accuracy(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.mean(y_true == y_pred))


def oversample_equal(X: np.ndarray, y: np.ndarray, seed: int = 0) -> tuple[np.ndarray, np.ndarray]:
    """Random oversampling to balance class counts (train only)."""
    rng = np.random.default_rng(seed)
    classes, counts = np.unique(y, return_counts=True)
    max_n = int(np.max(counts))
    X_out = []
    y_out = []
    for c in classes:
        idx = np.where(y == c)[0]
        if idx.size == 0:
            continue
        reps = int(np.ceil(max_n / idx.size))
        idx_rep = np.tile(idx, reps)
        idx_rep = rng.permutation(idx_rep)[:max_n]
        X_out.append(X[idx_rep])
        y_out.append(np.full(max_n, c, dtype=y.dtype))
    Xb = np.concatenate(X_out, axis=0)
    yb = np.concatenate(y_out, axis=0)
    perm = rng.permutation(len(yb))
    return Xb[perm], yb[perm]




def standardize_fit(X: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    mu = X.mean(axis=0, keepdims=True)
    sd = X.std(axis=0, keepdims=True) + 1e-9
    return mu, sd

def standardize_apply(X: np.ndarray, mu: np.ndarray, sd: np.ndarray) -> np.ndarray:
    return (X - mu) / sd

def rank_features_rf(X_tr: np.ndarray, y_tr: np.ndarray, seed: int = 0) -> np.ndarray:
    """Rank features by RandomForest feature_importances_ (cheap, deterministic)."""
    rf = RandomForestClassifier(
        n_estimators=400,
        random_state=seed,
        class_weight="balanced_subsample",
        n_jobs=1,
        max_features="sqrt",
    )
    rf.fit(X_tr, y_tr)
    imp = rf.feature_importances_
    order = np.argsort(imp)[::-1]
    return order


def dedup_by_corr(X_tr: np.ndarray, order: np.ndarray, corr_th: float = 0.90) -> np.ndarray:
    """Greedy remove highly correlated features (absolute Pearson corr)."""
    kept = []
    # precompute corr on training
    # (use float64 to be safe)
    X = X_tr.astype(np.float64)
    for j in order:
        if len(kept) == 0:
            kept.append(int(j))
            continue
        v = X[:, j]
        ok = True
        for k in kept:
            u = X[:, k]
            # handle constant features
            if np.std(v) < 1e-12 or np.std(u) < 1e-12:
                continue
            c = np.corrcoef(u, v)[0, 1]
            if np.abs(c) >= corr_th:
                ok = False
                break
        if ok:
            kept.append(int(j))
    return np.asarray(kept, dtype=int)


@dataclass
class EdgeResult:
    best_k: int
    selected_idx: list[int]
    selected_names: list[str]
    metrics: dict


def select_topk_features(
    X: np.ndarray,
    y: np.ndarray,
    idx_tr: np.ndarray,
    idx_va: np.ndarray,
    k_min: int = 5,
    k_max: int = 7,
    seed: int = 0,
    corr_th: float = 0.90,
) -> tuple[int, np.ndarray, list[int], list[float]]:
    """Select feature subset size K using val Macro-F1, constrained to [k_min, k_max].

    Procedure (train/val only):
    1) rank by RF importance on train
    2) de-duplicate by correlation on train
    3) for K in [k_min..k_max]: train softmax on balanced train, evaluate val Macro-F1
    4) choose K with the best val Macro-F1 (tie-break: smaller K).
    """
    X_tr = X[idx_tr]
    y_tr = y[idx_tr]
    X_va = X[idx_va]
    y_va = y[idx_va]

    mu, sd = standardize_fit(X_tr)
    X_tr = standardize_apply(X_tr, mu, sd)
    X_va = standardize_apply(X_va, mu, sd)

    order = rank_features_rf(X_tr, y_tr, seed=seed)
    order = dedup_by_corr(X_tr, order, corr_th=corr_th)

    n_avail = int(order.size)
    if n_avail == 0:
        raise RuntimeError("No features available after correlation filtering")

    k_min_eff = int(max(1, min(k_min, n_avail)))
    k_max_eff = int(max(k_min_eff, min(k_max, n_avail)))
    k_grid = list(range(k_min_eff, k_max_eff + 1))

    n_class = int(np.max(y) + 1)
    f1_list: list[float] = []
    for k in k_grid:
        sel = order[:k]
        Xb, yb = oversample_equal(X_tr[:, sel], y_tr, seed=seed)
        clf = LogisticRegression(
            multi_class="multinomial",
            solver="lbfgs",
            max_iter=6000,
            random_state=seed,
        )
        clf.fit(Xb, yb)
        yv = clf.predict(X_va[:, sel])
        f1_list.append(macro_f1(y_va, yv, n_class))

    best_f1 = float(np.max(f1_list))
    # tie-break by smaller K
    best_pos = int(np.where(np.asarray(f1_list) == best_f1)[0][0])
    best_k = int(k_grid[best_pos])
    return best_k, order[:best_k], k_grid, f1_list
def run_edge_baselines(
    X: np.ndarray,
    y: np.ndarray,
    idx_tr: np.ndarray,
    idx_va: np.ndarray,
    idx_te: np.ndarray,
    k_min: int = 5,
    k_max: int = 7,
    seed: int = 0,
) -> EdgeResult:
    n_class = int(np.max(y) + 1)

    best_k, sel, k_grid, val_f1_curve = select_topk_features(
        X,
        y,
        idx_tr,
        idx_va,
        k_min=k_min,
        k_max=k_max,
        seed=seed,
        corr_th=0.90,
    )

    names = feature_names_allreal_v4(fs=50)
    sel_names = [names[i] for i in sel.tolist()]

    # train final models on train+val (balanced)
    idx_tv = np.concatenate([idx_tr, idx_va])

    X_tv = X[idx_tv][:, sel]
    y_tv = y[idx_tv]
    X_te = X[idx_te][:, sel]
    y_te = y[idx_te]
    mu, sd = standardize_fit(X_tv)
    X_tv = standardize_apply(X_tv, mu, sd)
    X_te = standardize_apply(X_te, mu, sd)

    Xb, yb = oversample_equal(X_tv, y_tv, seed=seed)

    # 1) Softmax (multinomial logistic regression)
    softmax = LogisticRegression(
        multi_class="multinomial",
        solver="lbfgs",
        max_iter=4000,
        random_state=seed,
    )
    softmax.fit(Xb, yb)
    yp_soft = softmax.predict(X_te)

    # 2) Linear SVM
    svm = LinearSVC(random_state=seed, C=1.0, dual="auto", max_iter=10000)
    svm.fit(Xb, yb)
    yp_svm = svm.predict(X_te)

    # 3) Decision tree (small, interpretable)
    dt = DecisionTreeClassifier(random_state=seed, max_depth=6)
    dt.fit(Xb, yb)
    yp_dt = dt.predict(X_te)

    metrics = {
        "feature_k": int(best_k),
        "k_grid": [int(k) for k in k_grid],
        "val_macroF1_curve": [float(x) for x in val_f1_curve],
        "selected_idx": sel.tolist(),
        "selected_names": sel_names,
        "scaler_mu": mu.reshape(-1).tolist(),
        "scaler_sd": sd.reshape(-1).tolist(),
        "softmax_coef": softmax.coef_.tolist(),
        "softmax_intercept": softmax.intercept_.tolist(),
        "softmax": {
            "acc": accuracy(y_te, yp_soft),
            "macro_f1": macro_f1(y_te, yp_soft, n_class),
            "cm": confusion_matrix(y_te, yp_soft, labels=list(range(n_class))).tolist(),
        },
        "svm": {
            "acc": accuracy(y_te, yp_svm),
            "macro_f1": macro_f1(y_te, yp_svm, n_class),
            "cm": confusion_matrix(y_te, yp_svm, labels=list(range(n_class))).tolist(),
        },
        "dt": {
            "acc": accuracy(y_te, yp_dt),
            "macro_f1": macro_f1(y_te, yp_dt, n_class),
            "cm": confusion_matrix(y_te, yp_dt, labels=list(range(n_class))).tolist(),
        },
    }

    return EdgeResult(best_k=int(best_k), selected_idx=sel.tolist(), selected_names=sel_names, metrics=metrics)


def build_feature_matrix(xyz_list: list[np.ndarray]) -> np.ndarray:
    names = feature_names_allreal_v4(fs=50)
    X = np.zeros((len(xyz_list), len(names)), dtype=np.float64)
    for i, xyz in enumerate(xyz_list):
        X[i] = extract_features_allreal_v4(xyz, fs=50)
    return X


def main():
    import argparse
    import scipy.io as sio

    ap = argparse.ArgumentParser()
    ap.add_argument("--mat", required=True)
    ap.add_argument("--split", required=True, help="split_indices.npz")
    ap.add_argument("--out", required=True, help="output json path")
    ap.add_argument("--kmin", type=int, default=5)
    ap.add_argument("--kmax", type=int, default=7)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    # load
    mat = sio.loadmat(args.mat)
    PD = mat["ProcessedData"]
    TL = mat["targetLength"]

    xyz_list = []
    y_list = []
    for c in range(PD.shape[1]):
        cell = PD[0, c]
        tl = np.array(TL[0, c]).reshape(-1)
        for i in range(cell.shape[1]):
            T = int(tl[i])
            xyz = np.asarray(cell[0, i], dtype=np.float64)[:T, :]
            xyz_list.append(xyz)
            y_list.append(c)
    y = np.asarray(y_list, dtype=int)

    sp = np.load(args.split)
    idx_tr = sp["idx_tr"].astype(int)
    idx_va = sp["idx_va"].astype(int)
    idx_te = sp["idx_te"].astype(int)

    X = build_feature_matrix(xyz_list)

    res = run_edge_baselines(X, y, idx_tr, idx_va, idx_te, k_min=args.kmin, k_max=args.kmax, seed=args.seed)

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(json.dumps(res.metrics, ensure_ascii=False, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()